version: "3.7"

services:
  nginx:
    build:
      context: ./docker/nginx # Dockerfile保存場所
    container_name: nginx # コンテナ名
    tty: true
    restart: always
    volumes: # mount workdir
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_NGINX_CONTAINER}
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php

  proxy: # nginxと同じイメージ
    build:
      context: ./docker/nginx # Dockerfile保存場所
    container_name: proxy # コンテナ名
    tty: true
    ports: # ポート接続
      - ${HOST_PROXY_PORT}:${CONTAINER_PROXY_PORT}
    volumes:
      - ./docker/nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf
    depends_on:
      - nginx

  php:
    build:
      context: ./docker/php # Dockerfile保存場所
    container_name: php # コンテナ名
    tty: true
    ports: # ポート接続
      - ${HOST_PHP_PORT}:${CONTAINER_PHP_PORT}
    volumes:
      - ${APP_CODE_PATH_HOST}:${php_CODE_PATH_CONTAINER}
    depends_on:
      - db

  db:
    build:
      context: ./docker/mysql # Dockerfile保存場所
    container_name: db # コンテナ名
    tty: true
    ports: # ポート接続
      - ${DB_HOST_PORT}:${DB_HOST_PORT}
    volumes: # mount workdir
      - ./data:/var/lib/mysql
      - ${DB_PATH_HOST}/my.cnf:/etc/mysql/conf.d/my.cnf
      - ${DB_PATH_HOST}/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
